apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels: 
    app: postgres
    type: hostpath
  name: postgres-pv-claim
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi